# Generated by Django 5.0.3 on 2024-03-10 00:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="interests",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("Computer Science", "Computer Science"),
                        ("Mathematics", "Mathematics"),
                        ("Physics", "Physics"),
                        ("Chemistry", "Chemistry"),
                        ("Biology", "Biology"),
                        ("Medicine", "Medicine"),
                        ("Engineering", "Engineering"),
                        ("Business", "Business"),
                        ("Economics", "Economics"),
                        ("Law", "Law"),
                        ("Politics", "Politics"),
                        ("History", "History"),
                        ("Philosophy", "Philosophy"),
                        ("Psychology", "Psychology"),
                        ("Art", "Art"),
                        ("Music", "Music"),
                        ("Literature", "Literature"),
                        ("Language", "Language"),
                        ("Sports", "Sports"),
                        ("Cooking", "Cooking"),
                        ("Traveling", "Traveling"),
                        ("Fashion", "Fashion"),
                        ("Movies", "Movies"),
                        ("Games", "Games"),
                        ("Technology", "Technology"),
                        ("Science", "Science"),
                        ("Environment", "Environment"),
                        ("Social", "Social"),
                    ],
                    max_length=512,
                ),
                default=list,
                size=None,
            ),
        ),
    ]
