# Generated by Django 5.0.3 on 2024-03-10 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_user_interests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="host",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="host",
                related_query_name="host",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
