# Generated by Django 5.0.3 on 2024-03-09 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_space_description_space_image_url_space_rating_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="space",
            name="rating",
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.FloatField()),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        related_query_name="rating",
                        to="backend.space",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        related_query_name="rating",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
