# Generated by Django 5.0.3 on 2024-03-10 04:59

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_alter_booking_host"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventObjective",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("goal_text", models.TextField()),
                (
                    "todo_list",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), default=list, size=None
                    ),
                ),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.eventobjective",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
