# Generated by Django 5.0.3 on 2024-03-09 17:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_remove_space_rating_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="space",
        ),
        migrations.AddField(
            model_name="event",
            name="booking",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="backend.booking",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="end_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="max_attendees",
            field=models.PositiveIntegerField(default=int()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="name",
            field=models.CharField(default="", max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="start_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
