# Generated by Django 5.0.3 on 2024-03-09 18:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0004_remove_event_space_event_booking_event_end_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="attendees",
        ),
        migrations.AddField(
            model_name="event",
            name="attendees",
            field=models.ManyToManyField(
                related_name="attends",
                related_query_name="attend",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
