# Generated by Django 5.0.3 on 2024-03-09 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0005_remove_booking_attendees_event_attendees"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="host",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                related_query_name="event",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
