# Generated by Django 5.0.3 on 2024-03-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0005_alter_eventobjective_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="summary",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
