# Generated by Django 5.0.3 on 2024-03-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0006_event_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="checked_in",
            field=models.BooleanField(default=False),
        ),
    ]
