# Generated by Django 5.0.3 on 2024-03-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0006_event_host"),
    ]

    operations = [
        migrations.AlterField(
            model_name="space",
            name="image_url",
            field=models.URLField(),
        ),
    ]
