# Generated by Django 5.0.3 on 2024-03-10 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0007_booking_checked_in"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventobjective",
            name="event",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="objective",
                to="backend.event",
            ),
        ),
    ]
