# Generated by Django 5.0.3 on 2024-03-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0008_alter_eventobjective_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="space",
            name="type",
            field=models.CharField(
                choices=[
                    ("SILENT", "Silent"),
                    ("BUSY", "Busy"),
                    ("MEETING", "Meeting"),
                ],
                max_length=20,
            ),
        ),
    ]
