# Generated by Django 5.0.3 on 2024-03-10 06:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0009_alter_space_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventobjective",
            name="todo_list",
        ),
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.TextField()),
                ("completed", models.BooleanField(default=False)),
                (
                    "event_objective",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="todos",
                        to="backend.eventobjective",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
