# Generated by Django 5.0.3 on 2024-03-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0009_rename_event_eventmessage_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="space",
            name="latitude",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="space",
            name="longitude",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="space",
            name="rate",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Rating",
        ),
    ]
