# Generated by Django 5.0.3 on 2024-03-10 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0010_remove_eventobjective_todo_list_todo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="text",
            new_name="content",
        ),
    ]
