# Generated by Django 5.0.3 on 2024-03-09 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0010_space_latitude_space_longitude_space_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="space",
            name="status",
            field=models.CharField(
                choices=[("QUITE", "Quite"), ("BUSY", "Busy"), ("MEETING", "Meeting")],
                default="BUSY",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
