# Generated by Django 5.0.3 on 2024-03-09 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0011_space_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="space",
            old_name="status",
            new_name="type",
        ),
    ]
