# Generated by Django 5.0.3 on 2024-03-10 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0011_rename_text_todo_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventobjective",
            name="goal_text",
        ),
    ]
